### ISSUE TITLE
Mismatch between code and paper

### ISSUE THREAD

**Issue by JiahaoHuang99** [icon-lab/FDB#1]
Thansk for you nice job!

I got a question about the code. In the defination of `DiffusionBridge`, I can't find any usage about Gaussian noise, but in the main paper,  both forward and reverse process contain Gaussian noise.

Thanks a lot and look forward to your answer.

**Comment by usamamirza0** [comment]
We are currently testing many variations to optimize our method. The current version does not contain Gaussian noise but we will soon release a comprehensive version fixing this issue.
